# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [3]:
#Assignment 1: Array Creation and Manipulation
#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

array = np.random.randint(1,21,size = (5,5))
print("Original Array = ",array)

array[:,2] = 1
print("Modified Array = ",array)


Original Array =  [[ 8  1 11  4 15]
 [19 19 13  3 17]
 [20  8 11 11  7]
 [ 2 16  6 13  6]
 [18 17  5 16  7]]
Modified Array =  [[ 8  1  1  4 15]
 [19 19  1  3 17]
 [20  8  1 11  7]
 [ 2 16  1 13  6]
 [18 17  1 16  7]]


In [7]:
#Assignment 1: Array Creation and Manipulation
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

array = np.arange(1,17).reshape((4,4))
print("Original Array = ",array)

np.fill_diagonal(array, 0)
print("Modified Array = ",array)

Original Array =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array =  [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [8]:
#Assignment 2: Array Indexing and Slicing
#1.Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

array = np.arange(1,37).reshape((6,6))
print("Full Array = ",array)

sub_array = array[2:5,1:4]
print("Sub_Array = ",sub_array)

Full Array =  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub_Array =  [[14 15 16]
 [20 21 22]
 [26 27 28]]


In [11]:
#Assignment 2: Array Indexing and Slicing
#2.Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

array = np.random.randint(1,21,size = (5,5))
print("Array = ",array)

border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements = ",border_elements)



Array =  [[ 5  8  2  5 14]
 [ 5 20 14 11 20]
 [13 13 13  7  6]
 [16  3  7 12  8]
 [ 9 11  2  4  3]]
Border elements =  [ 5  8  2  5 14  9 11  2  4  3  5 13 16 20  6  8]


In [15]:
#Assignment 3: Array Operations
#1.Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

arr1 = np.random.randint(1,10, size = (3, 4))
arr2 = np.random.randint(1,10, size = (3, 4))

print("Array1 = ",arr1)
print("Array2 = ",arr2)
print("element-wise addition = ",arr1 + arr2)
print("element-wise subtraction = ",arr1-arr2)
print("element-wise multiplication = ",arr1*arr2)
print("element wise division = ",arr1/arr2)

Array1 =  [[8 5 2 5]
 [6 1 5 9]
 [9 9 7 5]]
Array2 =  [[6 6 2 3]
 [8 7 1 4]
 [5 6 5 4]]
element-wise addition =  [[14 11  4  8]
 [14  8  6 13]
 [14 15 12  9]]
element-wise subtraction =  [[ 2 -1  0  2]
 [-2 -6  4  5]
 [ 4  3  2  1]]
element-wise multiplication =  [[48 30  4 15]
 [48  7  5 36]
 [45 54 35 20]]
element wise division =  [[1.33333333 0.83333333 1.         1.66666667]
 [0.75       0.14285714 5.         2.25      ]
 [1.8        1.5        1.4        1.25      ]]


In [17]:
#Assignment 3: Array Operations
#Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
array = np.arange(1,17).reshape((4,4))
print("Array = ",array)

row_sum = np.sum(array, axis = 1)
col_sum = np.sum(array, axis = 0)
print("Sum of all elements in row = ",row_sum)
print("Sum of all elements in Column = ",col_sum)

Array =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of all elements in row =  [10 26 42 58]
Sum of all elements in Column =  [28 32 36 40]


In [21]:
#Assignment 4: Statistical Operations
#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation,normalized_array and variance of the array.
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array.
array = np.random.randint(1,10,size=(5,5))
print("Array = ",array)

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
var = np.var(array)
normalized_array = (array-mean)/std_dev
print("Mean = ",mean)
print("Median = ",median)
print("standard deviation = ",std_dev)
print("variance = ",var)
print("Normalized_array = ",normalized_array)

Array =  [[4 2 1 4 8]
 [2 3 5 2 4]
 [3 5 1 6 1]
 [4 5 9 1 6]
 [2 9 9 1 4]]
Mean =  4.04
Median =  4.0
standard deviation =  2.5687350972803715
variance =  6.598400000000001
Normalized_array =  [[-0.01557187 -0.79416519 -1.18346185 -0.01557187  1.54161478]
 [-0.79416519 -0.40486853  0.3737248  -0.79416519 -0.01557187]
 [-0.40486853  0.3737248  -1.18346185  0.76302146 -1.18346185]
 [-0.01557187  0.3737248   1.93091145 -1.18346185  0.76302146]
 [-0.79416519  1.93091145  1.93091145 -1.18346185 -0.01557187]]


In [32]:
#Assignment 5: Broadcasting
#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

arr = np.random.randint(1,10,size=(3,3))
print("Array = ",arr)
row_arr = np.random.randint(1,10,size=(3,))
print("Row Array = ",row_arr)

final_arr = arr + row_arr[:, np.newaxis]
print("Final Array = ",final_arr)

Array =  [[5 4 7]
 [9 8 4]
 [1 6 6]]
Row Array =  [5 4 1]
Final Array =  [[10  9 12]
 [13 12  8]
 [ 2  7  7]]


In [31]:
#Assignment 5: Broadcasting
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr = np.random.randint(1,10,size=(4,4))
print("Array = ",arr)

col_arr = np.random.randint(1,10,size=(4,))
print("Row Array = ",col_arr)

final_arr = arr - col_arr[:, np.newaxis]
print("Final Array = ",final_arr)

Array =  [[2 2 2 5]
 [8 5 9 9]
 [8 4 1 2]
 [4 4 1 4]]
Row Array =  [2 9 3 8]
Final Array =  [[ 0  0  0  3]
 [-1 -4  0  0]
 [ 5  1 -2 -1]
 [-4 -4 -7 -4]]


In [34]:
#Assignment 6: Linear Algebra
#Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

matrix = np.random.randint(1,10,size=(3,3))
print("Array = ",arr)

determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Array =  [[9 2 5]
 [1 6 6]
 [9 4 6]]
Determinant: 187.00000000000003
Inverse:
[[ 0.17647059 -0.11764706  0.05882353]
 [ 0.14973262  0.11229947 -0.10160428]
 [-0.30481283  0.02139037  0.17112299]]
Eigenvalues: [15.13384914+0.j          2.43307543+2.53703587j  2.43307543-2.53703587j]


In [36]:
#Assignment 6: Linear Algebra
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

arr1 = np.random.randint(1,10,size=(2,3))
print("Array1 = ",arr1)
arr2 = np.random.randint(1,10,size=(3,2))
print("Array1 = ",arr2)

matrix_multiplication = np.dot(arr1, arr2)
print("matrix multiplication = ",matrix_multiplication)

Array1 =  [[2 4 1]
 [1 2 9]]
Array1 =  [[7 8]
 [7 5]
 [1 5]]
matrix multiplication =  [[43 41]
 [30 63]]


In [39]:
#Assignment 7: Advanced Array Manipulation
#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
arr = np.arange(1,10).reshape((3,3))
print("Array = ",arr)
arr1 = arr.reshape((1, 9))
print("Reshape the array to shape (1, 9) = ",arr1)
arr2 = arr1.reshape((9, 1))
print("Reshape the array to shape (9, 1) = ",arr2)

Array =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshape the array to shape (1, 9) =  [[1 2 3 4 5 6 7 8 9]]
Reshape the array to shape (9, 1) =  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [40]:
#Assignment 7: Advanced Array Manipulation
#2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

arr = np.random.randint(1,10,size=(5,5))
print("Array = ",arr)

flatten_arr = arr.flatten()
print("Flatten the array = ",flatten_arr)

reshaped_arr = flatten_arr.reshape(5,5)
print("Reshaped array = ",reshaped_arr)

Array =  [[2 4 6 7 7]
 [3 7 2 5 7]
 [5 4 2 1 1]
 [1 6 3 5 4]
 [4 4 4 8 9]]
Flatten the array =  [2 4 6 7 7 3 7 2 5 7 5 4 2 1 1 1 6 3 5 4 4 4 4 8 9]
Reshaped array =  [[2 4 6 7 7]
 [3 7 2 5 7]
 [5 4 2 1 1]
 [1 6 3 5 4]
 [4 4 4 8 9]]


In [41]:
#Assignment 8:Fancy Indexing and Boolean Indexing
#1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

arr = np.random.randint(1,10,size=(5,5))
print("Array = ",arr)

corners = arr[[0,0,-1,-1],[0,-1,0,-1]]
print("The elements at the corners of the array = ",corners)

Array =  [[4 6 3 6 8]
 [4 9 4 7 2]
 [7 3 7 5 5]
 [1 2 9 5 9]
 [5 7 5 5 6]]
The elements at the corners of the array =  [4 8 5 6]


In [42]:
#Assignment 8:Fancy Indexing and Boolean Indexing
#Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

arr = np.random.randint(1,10,size=(4,4))
print("Array = ",arr)

arr[arr > 10] = 10
print("Modified Array = ",arr)


Array =  [[5 8 1 3]
 [8 6 7 1]
 [6 5 5 6]
 [3 5 4 8]]
Modified Array =  [[5 8 1 3]
 [8 6 7 1]
 [6 5 5 6]
 [3 5 4 8]]


In [43]:
#Assignment 9: Structured Arrays
#1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array = ",data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age = ",sorted_data)


Original array =  [('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age =  [('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [49]:
#Assignment 9: Structured Arrays
#2.Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
data_type = [('x','i4'),('y','i4')]
data = np.array([(2,3),(3,5),(1,2)],dtype=data_type)
print("Original array = ",data)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances = ",distances)

Original array =  [(2, 3) (3, 5) (1, 2)]
Euclidean distances =  [[0.         2.23606798 1.41421356]
 [2.23606798 0.         3.60555128]
 [1.41421356 3.60555128 0.        ]]


In [52]:
#Assignment 10: Masked Arrays
#1. Create a masked array of shapes (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

import numpy.ma as ma

arr = np.random.randint(1,10,size=(4,4))
print("Array = ",arr)

masked_arr = ma.masked_greater(arr,10)
print("Masked Array = ",masked_arr)

sum_unmasked = masked_arr.sum()
print("Unmasked Array sum = ",sum_unmasked)


Array =  [[1 9 7 5]
 [5 2 6 4]
 [1 5 1 7]
 [4 5 9 9]]
Masked Array =  [[1 9 7 5]
 [5 2 6 4]
 [1 5 1 7]
 [4 5 9 9]]
Unmasked Array sum =  80


In [53]:
#Assignment 10: Masked Arrays
#2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements
array = np.random.randint(1, 21, size=(3, 3))
print("Original array:",array)

masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Masked array:",masked_array)

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:",masked_array)


Original array: [[ 1  7 19]
 [ 6  1 10]
 [18  5  5]]
Masked array: [[-- 7 19]
 [6 -- 10]
 [18 5 --]]
Modified masked array: [[10  7 19]
 [ 6 10 10]
 [18  5 10]]
